services:


  db:
    image: mysql:8.3.0
    container_name: mysql_db_Habit_Tracker
    command: mysqld --default_authentication_plugin=caching_sha2_password

    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: ${DB_PORT}


    ports:
      - "${DB_EXPOSE_PORT}:${DB_PORT}"

    expose:
      - ${DB_PORT}

    networks:
      - Habit_Tracker_network

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$$MYSQL_USER", "-p$$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


networks:
  Habit_Tracker_network:
    driver: bridge

volumes:
  mysql_data:
  kafka-persistence:

